security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\UserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Par défaut, les hachages de mot de passe sont intensifs en ressources et prennent du temps. Cependant, 
            # dans les tests, les hachages sécurisés ne sont pas importants, gaspillent des ressources et augmentent 
            # les temps de test. Les valeurs suivantes réduisent le travail au minimum.
            Symfony\Component\Security\Core\User\UserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse possible pour bcrypt
                time_cost: 3 # Valeur la plus basse possible pour argon
                memory_cost: 10 # Valeur la plus basse possible pour argon